/*
 * conf_i2c.h
 *
 * Created: 14/1/2565 12:05:31
 *  Author: parisa
 */ 


#ifndef CONF_I2C_H_
#define CONF_I2C_H_

#define CONF_I2C_MODULE_ENABLE

#if defined (CONF_I2C_MODULE_ENABLE)

#define CONF_I2C_MODULE				EXT1_I2C_MODULE
#define CONF_I2C_SERCOM_PINMUX_PAD0	EXT1_I2C_SERCOM_PINMUX_PAD0
#define CONF_I2C_SERCOM_PINMUX_PAD1	EXT1_I2C_SERCOM_PINMUX_PAD1
#define	CONF_I2C_SERCOM_DMAC_ID_TX	EXT1_I2C_SERCOM_DMAC_ID_TX
#define CONF_I2C_SERCOM_DMAC_ID_RX	EXT1_I2C_SERCOM_DMAC_ID_RX

#endif /* CONF_I2C_MODULE_ENABLE */




#endif /* CONF_I2C_H_ */